### ISSUE TITLE
zip compression and download

### ISSUE THREAD

**Issue by kudomarkos** [jnsougata/filebox#8]
Hello filebox team!
Yesterday I upgrade the new version of filebox in deta space.
I had several mp3 in different folders. I tried to download every folder as a zip file.
A easy summing menu on right showed me the status of the creation of the zip files.
Finally I got all the zips downloaded. The issue here was, 16% of the mp3 into those zip files were 44Kb files with the name of the mp3. Of course they aren't mp3...
I tried to do the same with a folder full of jpgs. Again the 25% of the files were 44Kb files not corresponding with the pics i had in filebox.
So I think something is wrong with this feature.
I can't know if it is a zip problem, a temp folder problem.. etc..

Anyway thanks for sharing this incredible app. 
Hugs from spain

**Comment by jnsougata** [comment]
Hi @kudomarkos it's a known bug. This app out of development for a while. We will fix it in V2.
